version: "2.4"

####################
####################
services:
  fc-exploitation:
    hostname: fc-exploitation
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app/fc-exploitation
    depends_on:
      - "pg-exploitation"
      - "mongo-fcp-low"
      - "squid"
      - "rnipp"
      - "csmr-user-preferences-high"
      - "broker"
      - "csmr-hsm"
      - "haproxy"
    volumes:
      - "${VOLUMES_DIR}/src/fc-apps:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/fc-apps/insee-db:/usr/share/insee-db"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/shared/.env/postgres.env"
      - "${COMPOSE_DIR}/core-legacy/.env/exploitation-legacy.env"
      - "${COMPOSE_DIR}/fcp-low/.env/mongo-fcp-low.env"
    networks:
      - exploitation
      - data
    command: "pm2 logs"

  pg-exploitation:
    image: postgres:11
    environment:
      - "POSTGRES_DB=pg-db"
      - "POSTGRES_USER=pg-user"
      - "POSTGRES_PASSWORD=pg-password"
    networks:
      - data
