version: '2.4'

####################
####################
services:
  # ####################
  # # Site usagers
  # ####################
  usagers:
    hostname: usager
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - 'squid'
    volumes:
      - '${VOLUMES_DIR}/src/usagers:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/usagers/.env/usagers.env'
    networks:
      - public
    command: 'tail -f /dev/null'
